db01:
  environment:
    CLUSTER_MEMBERS: db01.${rancher_stack_name},db02.${rancher_stack_name},db03.${rancher_stack_name}
    RANCHER_STACK: ${rancher_stack_name}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=${rancher_stack_name}/db02,io.rancher.stack_service.name=${rancher_stack_name}/db03
  command:
  - --wsrep-new-cluster
  hostname: db01
  image: toughiq/mariadb-cluster:rancher
db02:
  environment:
    CLUSTER_MEMBERS: db01.${rancher_stack_name},db02.${rancher_stack_name},db03.${rancher_stack_name}
    RANCHER_STACK: ${rancher_stack_name}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=${rancher_stack_name}/db01,io.rancher.stack_service.name=${rancher_stack_name}/db03
  image: toughiq/mariadb-cluster:rancher
  hostname: db02
db03:
  environment:
    CLUSTER_MEMBERS: db01.${rancher_stack_name},db02.${rancher_stack_name},db03.${rancher_stack_name}
    RANCHER_STACK: ${rancher_stack_name}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=${rancher_stack_name}/db01,io.rancher.stack_service.name=${rancher_stack_name}/db02
  image: toughiq/mariadb-cluster:rancher
  hostname: db03
