db01:
  environment:
    CLUSTER_MEMBERS: db01,db02,db03
    MYSQL_ROOT_PASSWORD: "${mysql_root_password}"
    MYSQL_DATABASE: "${mysql_database}"
    MYSQL_USER: "${mysql_user}"
    MYSQL_PASSWORD: "${mysql_password}"
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/db02,io.rancher.stack_service.name=$${stack_name}/db03
  command:
  - --wsrep-new-cluster
  hostname: db01
  image: toughiq/mariadb-cluster:rancher
db02:
  environment:
    CLUSTER_MEMBERS: db01,db02,db03
    RANCHER_STACK: ${RANCHER_STACK}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/db01,io.rancher.stack_service.name=$${stack_name}/db03
  image: toughiq/mariadb-cluster:rancher
  hostname: db02
db03:
  environment:
    CLUSTER_MEMBERS: db01,db02,db03
    RANCHER_STACK: ${RANCHER_STACK}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/db01,io.rancher.stack_service.name=$${stack_name}/db02
  image: toughiq/mariadb-cluster:rancher
  hostname: db03
maxscale:
  environment:
    BACKEND_SERVER_LIST: db01,db02,db03
  labels:
    io.rancher.container.pull_image: always
  image: toughiq/maxscale
max-lb:
  ports:
  - 3306:3306/tcp
  labels:
    io.rancher.scheduler.global: 'true'
  image: rancher/load-balancer-service
  links:
  - maxscale:maxscale
