.catalog:
  name: MariaDB-Cluster
  version: v2.0 
  description: "MariaDB-Cluster based on MariaDB 10.1"
  minimum_rancher_version: v1.1.0
  questions:
    - variable: rancher_stack_name
      label: "Rancher Stack Name"
      description: "Must match the Rancher Stack Name of the Service to ensure proper DNS resolution in config."
      default: "mariadb-cluster"
      required: true
      type: string 
    - variable: maxscale_public_port
      label: "Public Port for MaxScale to listen on"
      description: "This port is exposed to the public by MaxScale"
      default: "3306"
      required: true
      type: int 

db01:
  scale: 1
db02:
  scale: 1
db03:
  scale: 1
maxscale:
  scale: 1
  health_check:
    port: ${maxscale_public_port}
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
