.catalog:
  name: MariaDB-Cluster
  version: v1.0 
  description: "MariaDB-Cluster based on MariaDB 10.1"
  minimum_rancher_version: v1.1.0
  questions:
    - variable: "mysql_root_password"
      type: string
      required: true
      label: "MySQL Root Password"
      description: "Password for MySQL Root User"
      default: "rootpass"
    - variable: "mysql_database"
      type: string
      required: true
      label: "MySQL Database Name"
      description: "Create MySQL Database"
      default: "mydb"
    - variable: "mysql_user"
      type: string
      required: true
      description: "Create MySQL User"
      label: "MySQL DB User"
      default: "myuser"
    - variable: "mysql_password"
      type: string
      required: true
      label: "MySQL DB Password"
      description: "Password for MySQL User"
      default: "mypass"
    - variable: maxscale_public_port
      label: "Public Port for MaxScale to listen on"
      description: "This port is exposed to the public by MaxScale"
      default: "3306"
      required: true
      type: int 

db01:
  scale: 1
  retain_ip: true
db02:
  scale: 1
  retain_ip: true
db03:
  scale: 1
  retain_ip: true
maxscale:
  scale: 1
  retain_ip: true
  health_check:
    port: 3306
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
max-lb:
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
